version: '3.7'

services:  
  # Instance 1
  redis-sentinel-1:
    container_name: redis-sentinel-1
    build: 
      context: ./redis-sentinel
    ports:
      - '26379:26379'
  # Instance 1
  redis-sentinel-2:
    container_name: redis-sentinel-2
    build: 
      context: ./redis-sentinel
    ports:
      - '26380:26379'
