version: '2.2'
services:
  sentinel1:
    image: redis:6
    container_name: redis-sentinel-1
    ports:
      - '26379:26379'
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      # - ./sentinel_data/tmp:/tmp
      - ./sentinel_conf/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      - rdsentinel-network
  # sentinel2:
  #   image: redis:6
  #   container_name: redis-sentinel-2
  #   ports:
  #   - '26380:26379'
  #   command: redis-sentinel /usr/local/etc/redis/sentinel.conf
  #   volumes:
  #     - ./sentinel_conf/sentinel2.conf:/usr/local/etc/redis/sentinel.conf
  #   networks:
  #     - rdsentinel-network
  # sentinel3:
  #   image: redis:6
  #   container_name: redis-sentinel-3
  #   ports:
  #     - '26381:26379'
  #   command: redis-sentinel /usr/local/etc/redis/sentinel.conf
  #   volumes:
  #     - ./sentinel_conf/sentinel3.conf:/usr/local/etc/redis/sentinel.conf
  #   networks:
  #     - rdsentinel-network
networks:
  rdsentinel-network:
    driver: bridge
volumes:
  sentinel_data:
    name: redis-vl
    driver: local
    external: true